### ISSUE TITLE
How can I passing Docker daemon to the slave？

### ISSUE THREAD

**Issue by ghost** [openfrontier/jenkins-swarm-maven-slave#1]
How can I passing Docker daemon to the slave？Support it？

```
docker run -d \
--name swarm-maven-slave1 \
-d openfrontier/jenkins-swarm-maven-slave \
-master http://jenkins:8080 -username jenkins -password jenkins \
-executors 1 
```

It's ok.

but, Exited (255)

```
docker run -d \
--name swarm-maven-slave2 \
-d openfrontier/jenkins-swarm-maven-slave \
-master http://jenkins:8080 -username jenkins -password jenkins \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /usr/bin/docker:/usr/bin/docker \
-executors 1
```

**Comment by thinkernel** [comment]
It might not works because some the distributions of the docker binary on your host depends on others *.so files. 
Here's an example on coreos which shows the docker binary has some dependencies which are not available in the images. In this case, only mount /usr/bin/docker into the container isn't quite enough.

```
~/ci $ ldd /usr/bin/docker
        linux-vdso.so.1 (0x00007fff9477d000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f032792f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0327580000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f032737c000)
        libdevmapper.so.1.02 => /lib64/libdevmapper.so.1.02 (0x00007f032712e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0326d83000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f0326b7b000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f0326955000)
        libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f0326666000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f032779d000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00007f032790b000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f0326461000)
```

If that is your case, the easiest way might be install the docker binary into the image. You can check the [Dockerfile ](https://github.com/openfrontier/jenkins-docker/blob/master/Dockerfile)of the openfrontier/jenkins project which can be an example on how to install it.

But, here is my another suggestion. The jenkins-swarm-maven-slave or the jenkins-swam-slave should merely works as a container to build your souce code. It might not be a good practice to trigger a DOCKER build in this container. You should use others Jenkins plugins to accomplish that kind of work.

**Comment by ghost** [comment]
I got it.
thank you very much.
